### ISSUE TITLE
[Bug] [possibles UpCloud server issue] code: 'ERR_UNHANDLED_REJECTION'

### ISSUE THREAD

**Issue by bachig26** [Thanatoslayer6/clistream#3]
```
clistream
Initialized Sflix constructor with User-Agent...
Using https://sflix.to as main site...
Initialized Actions...
Initialized Media player
No session file found, will create one if user saves...
√ Main Menu · SEARCH
√ Search a Movie/Tv-Show · psych
? Select from search ...
√ Select from search · Psych
√ Select · Season 2
√ Select · Episode 1: American Duos
√ Select a server · UpCloud
√ Select multiple subtitles · No items were selected
√ Select an action · NEXT
√ Select a server · UpCloud
Main key failed to decrypt source, trying next one(?)
√ Select multiple subtitles · No items were selected
{
  errcode: 5,
  verbose: 'Timeout',
  method: 'processTicksAndRejections()',
  arguments: [
    'https://t-eu-2.magnewscontent.org/_v9/a56dac17141ede71e774c38920e4660db28cd0ea5833436d400bf8b876fc779db0c58d2c8b20afce7d9769b286a6c6901a68447b1adb591aaf1101a0e56b8fbb4ca95d8a14706a650a6659981b7b21fdee3a9a0ecda462bbcc7b44c4ed092783603198e1cce80aae338d6fe7ee85604a89976eef61dd0fbb6be7cd47551d3abd/playlist.m3u8'
  ],
  stackTrace: 'Error\n' +
    '    at ErrorHandler.errorMessage (C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\clistream\\node_modules\\node-mpv\\lib\\error.js:79:18)\n' +
    '    at Socket.<anonymous> (C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\clistream\\node_modules\\node-mpv\\lib\\mpv\\mpv.js:163:32)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:324:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:297:9)\n' +
    '    at Readable.push (node:internal/streams/readable:234:10)\n' +
    '    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)'
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.12.1
```

**Comment by Thanatoslayer6** [comment]
Good day!

I believe this issue is not an UpCloud server issue but rather an mpv one, as you can see this app uses [node-mpv](https://github.com/j-holub/Node-MPV) for playing/adding subtitles to the videos but, within your error log I noticed that it had already scraped the video link. Perhaps you can update mpv or use the Chocolatey package to its latest version if considering you're using mpv <= 0.35.0 and maybe it should work?

Again, thanks for opening this issue but I think i'm just gonna close it now, also if you think this issue persists or if you have any further questions feel free to reopen that's all thanks 😌
